# Generated by Django 3.0.5 on 2020-04-20 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('teacher_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=50)),
                ('total_seats', models.IntegerField()),
                ('subject_details', models.CharField(max_length=50)),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.Teacher')),
            ],
            options={
                'unique_together': {('level', 'subject_name')},
            },
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_address', models.TextField()),
                ('student_phone', models.CharField(max_length=11)),
                ('subject', models.ManyToManyField(to='management_app.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('subject', models.ManyToManyField(to='management_app.Subject')),
            ],
        ),
    ]
