# Generated by Django 3.0.5 on 2020-04-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('09', 'Class 9 O level'), ('10', 'Class 10 O level'), ('11', 'AS level'), ('12', 'A2 level')], max_length=2),
        ),
    ]
