# Generated by Django 3.0.5 on 2020-04-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0002_auto_20200420_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
