# Generated by Django 3.0.5 on 2020-04-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0004_subject_subject_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_details',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
