# Generated by Django 3.0.5 on 2020-04-24 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0005_auto_20200420_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_address', models.TextField()),
                ('student_phone', models.CharField(max_length=11)),
                ('selected_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.Season')),
                ('selected_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.Subject')),
            ],
            options={
                'unique_together': {('student_name', 'selected_season', 'selected_subject')},
            },
        ),
    ]
