# Generated by Django 3.0.5 on 2020-04-25 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0007_auto_20200425_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='selected_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.Season'),
        ),
    ]
